# Generated by Django 3.2.9 on 2022-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajevi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caj',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='caj',
            name='stock',
            field=models.CharField(max_length=5),
        ),
    ]
