# Generated by Django 3.2.9 on 2022-01-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajevi', '0005_auto_20220123_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caj',
            name='price_with_shipping',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
