# Generated by Django 3.2.9 on 2022-02-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajevi', '0006_alter_caj_price_with_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='caj',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
